CallTracking.Web/Models/LeadSource.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CallTracking.Web.Models
{
    public class LeadSource
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IncomingNumberNational { get; set; }
        public string IncomingNumberInternational { get; set; }
        [Display(Name = "Forwarding Number")]
        public string ForwardingNumber { get; set; }
        public virtual IList<Lead> Leads { get; set; }
    }
}

CallTracking.Web/Controllers/LeadSourcesController.cs
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using CallTracking.Web.Domain.Twilio;
using CallTracking.Web.Models;
using CallTracking.Web.Models.Repository;
using HttpStatusCodeResult = System.Web.Mvc.HttpStatusCodeResult;

namespace CallTracking.Web.Controllers
{
    public class LeadSourcesController : Controller
    {
        private readonly IRepository<LeadSource> _repository;
        private readonly IRestClient _restClient;

        public LeadSourcesController()
            : this(new LeadSourcesRepository(), new RestClient()) { }

        public LeadSourcesController(IRepository<LeadSource> repository, IRestClient restClient)
        {
            _repository = repository;
            _restClient = restClient;
        }

        // POST: LeadSources/Create
        [HttpPost]
        public async Task<ActionResult> Create(string phoneNumber)
        {
            var twiMLApplicationSid = Credentials.TwiMLApplicationSid ?? await _restClient.GetApplicationSidAsync();
            var twilioNumber = await _restClient.PurchasePhoneNumberAsync(phoneNumber, twiMLApplicationSid);

            var leadSource = new LeadSource
            {
                IncomingNumberNational = twilioNumber.FriendlyName,
                IncomingNumberInternational = twilioNumber.PhoneNumber?.ToString()
            };

            _repository.Create(leadSource);

            return RedirectToAction("Edit", new {id = leadSource.Id});
        }

        // GET: LeadSources/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var leadSource = _repository.Find(id.Value);
            if (leadSource == null)
            {
                return HttpNotFound();
            }

            return View(leadSource);
        }

        // POST: LeadSources/Edit/
        [HttpPost]
        public ActionResult Edit(
            [Bind(Include = "Id,Name,IncomingNumberNational,IncomingNumberInternational,ForwardingNumber")]
            LeadSource leadSource)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(leadSource);
                return RedirectToAction("Index", new { Controller = "Dashboard" });
            }

            return View(leadSource);
        }
    }
}

CallTracking.Web/Views/LeadSources/Edit.cshtml
@model CallTracking.Web.Models.LeadSource

<div class="row">
    <div class="page-header">
        <h1>Edit lead source for @Model.IncomingNumberNational</h1>
    </div>
    <div class="col-md-9">
        @using (Html.BeginForm("Edit", "LeadSources", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
        {
            <div class="form-group">
                @Html.HiddenFor(x => x.Id)
                @Html.HiddenFor(x => x.IncomingNumberNational)
                @Html.HiddenFor(x => x.IncomingNumberInternational)
                @Html.LabelFor(x => x.Name, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.Name, new {@class = "form-control"})
                    <p class="help-block">E.g. "Downtown billboard"</p>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.ForwardingNumber, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.ForwardingNumber, new { @class = "form-control" })
                    <p class="help-block">People who call this lead source will be connected with this phone number. Must include international prefix - e.g. +1 555 555 55555</p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" value="Update lead source" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>