CallTracking.Web/Controllers/AvailablePhoneNumbersController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using CallTracking.Web.Domain.Twilio;

namespace CallTracking.Web.Controllers
{
    public class AvailablePhoneNumbersController : Controller
    {
        private readonly IRestClient _restClient;

        public AvailablePhoneNumbersController()
            : this(new RestClient())
        {}

        public AvailablePhoneNumbersController(IRestClient restClient)
        {
            _restClient = restClient;
        }

        // GET: AvailablePhoneNumbers
        public async Task<ActionResult> Index(string areaCode)
        {
            var phoneNumbers = await _restClient.SearchPhoneNumbersAsync(areaCode);

            return View(phoneNumbers);
        }
    }
}

CallTracking.Web/Controllers/DashboardController.cs
using System.Web.Mvc;
using CallTracking.Web.Models;
using CallTracking.Web.Models.Repository;

namespace CallTracking.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IRepository<LeadSource> _repository;

        public DashboardController()
            : this(new LeadSourcesRepository()) { }

        public DashboardController(IRepository<LeadSource> repository)
        {
            _repository = repository;
        }
        public ActionResult Index()
        {
            var leadSources = _repository.All();
            return View(leadSources);
        }
    }
}

CallTracking.Web/Views/Dashboard/Index.cshtml
@model IEnumerable<CallTracking.Web.Models.LeadSource>
           
<h1>Call Tracking with Twilio</h1>
<p>This app shows you how to implement a sample call tracking application with Twilio. Add a new phone number below to get started.</p>
<div class="row">
    <div class="col-md-5">
        <h2>Add a new number</h2>
        <p>Create a new lead source by purchasing a new phone number. Area code is optional.</p>
        @using (Html.BeginForm("Index", "AvailablePhoneNumbers", FormMethod.Get, new { @class = "form-inline", role = "form" }))
        {
            <div class="form-group">
                <label class="sr-only control-label" for="areaCode">Area code</label>
                <input id="areaCode" name="areaCode" type="text" class="form-control" value="415" maxlength="3"/>
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        }
        <h2>Add a new number</h2>
        <p>Create a new lead source by purchasing a new phone number. Area code is optional.</p>
        @if (@Model.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Incoming Number</th>
                        <th>Forwarding Number</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var leadSource in Model)
                {
                    <tr>
                        <td>@leadSource.Name</td>
                        <td>@leadSource.IncomingNumberNational</td>
                        <td>@leadSource.ForwardingNumber</td>
                        <td>
                            @Html.ActionLink("Edit", "edit", new {controller = "leadsources", id=leadSource.Id}, new {@class = "btn btn-default btn-xs" })
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p><b>Add a new number to populate this list</b></p>
        }
    </div>
    <div class="col-md-7">
        <h2>Charts</h2>
        <p>The latest statistics about how the lead sources are performing.</p>

        <div class="row">
            <div class="col-md-6">
                <h3>Calls by lead source</h3>
                <p>The number of incoming calls each lead source has received.</p>
                <canvas id="leads-by-source"></canvas>
            </div>

            <div class="col-md-6">
                <h3>Calls by city</h3>
                <p>The number of calls from different cities, based on Twilio call data</p>
                <canvas id="leads-by-city"></canvas>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/calltracking")
}